# Generated by Django 5.1.2 on 2024-10-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='important',
            new_name='importante',
        ),
    ]
