# Generated by Django 5.1.2 on 2024-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
